name: 'Flow Action'
description: 'Does flow checking'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  flow-bin:
    required: true
    description: 'Path to your flow library, probably node_modules/.bin/flow'
branding:
  icon: check-circle
  color: red
