name: 'Flow Action'
description: 'Does flow checking'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  flow-bin:
    required: true
    description: 'Path to your flow library, probably node_modules/.bin/flow'
  check-run-subtitle:
    required: false
    description: 'A subtitle to add to the check run when annotations are passed back to avoid overwriting each other'
branding:
  icon: check-circle
  color: red
